project: 
  type: website
  
website: 
  page-navigation: true
  title: "Medo do Crime e Insegurança" 
  site-url: "https://denisberte.github.io/mdc/" 
  repo-url: https://github.com/DenisBerte/mdc.git 
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    
  sidebar:
    logo: "images/logonipp.jpg"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nipp.ufsc.br/
        text: "NIPP/UFSC"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Apresentação
      - href: intro.qmd
        text: Introdução
      - href: teoria.qmd
        text: Teoria do medo do crime
      - href: metodologia.qmd
        text: Metodologia
      - href: resultados.qmd
        text: Resultados e Discussão
      - href: conclusao.qmd
        text: Conclusão
      - href: biblio.qmd
        text: Referências


format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
